### ISSUE TITLE
Running main

### ISSUE THREAD

**Issue by JTMaddux88** [ChangedNameTo/CFBPoll#4]
Thank you for the update. Still having an issue with it. I ran the code in the read me and am getting these errors. I'll attach a screenshot. Am I doing something  wrong? Thanks
<img width="1440" alt="Screen Shot 2019-12-04 at 11 22 02 AM" src="https://user-images.githubusercontent.com/54452708/70160426-72773600-1688-11ea-946f-3d893a2cae55.png">

_Originally posted by @JTMaddux88 in https://github.com/ChangedNameTo/CFBPoll/issues/3#issuecomment-561720258_

**Comment by wn-mitch** [comment]
@JTMaddux88 Hey Man! Is this still an issue? I just upgraded to use pandas instead of sql_lite
